/**
 * Smart Book resolver (Phase 5 — all 5 AutoSource kinds).
 *
 * Pure function that combines a Book's manual items with auto-resolved
 * items from `book.smartSources`. Manual items always render top, auto
 * items bottom (LOCKED #5c). The output is a flat sorted array of
 * `ResolvedBookItem` — same shape as BookItem plus `source` provenance
 * for the UI to differentiate (e.g., disable drag handle on auto items).
 *
 * INVARIANT (smart-book-prd §2): AutoSource is a "supplier", not a
 * member kind. All 5 source kinds resolve to note/wiki BookItems —
 * never label/tag/sticker entities themselves.
 *
 * Source kind map (PRD §2):
 *   - folder (kind=note)  → notes via reverse N:M (Note.folderIds)
 *   - category            → wikis via DAG (WikiArticle.categoryIds)
 *   - tag                 → notes + wikis (cross-entity, both .tags[])
 *   - label               → notes only (Note.labelId scalar)
 *   - sticker             → note/wiki members (sticker.members.kind filter)
 *
 * Spec: `.omc/plans/smart-book-prd.md` §5.3 + §5.10.
 */

import { generateKeyBetween } from "fractional-indexing"
import type {
  Book,
  BookItem,
  Note,
  Folder,
  WikiArticle,
  WikiCategory,
  Tag,
  Label,
  Sticker,
} from "@/lib/types"

/**
 * BookItem with source provenance. The `source` field is in-memory only
 * (NOT persisted) — it tells the UI whether the item came from
 * `book.items` (manual) or was auto-generated by a smartSource (auto).
 *
 * `sourceRefId` is set on auto items so the UI can route "remove" to
 * `addExcludeId(refId)` (auto) vs `removeItemFromBook(itemId)` (manual).
 */
export type ResolvedBookItem = BookItem & {
  source: "manual" | "auto"
  /** For auto items, the smartSource.refId that generated this item. */
  sourceRefId?: string
}

/**
 * Minimal store snapshot the resolver needs. Decouples from PlotState
 * for testability.
 *
 * Phase B+ added wiki entities for category source. Phase C-E added
 * tags/labels/stickers. All non-Phase-A fields are optional to keep
 * older callers (folder-only) backwards compatible — missing fields
 * cause that source kind to silently skip, never crash.
 */
export interface ResolverStore {
  notes: Note[]
  folders: Folder[]
  wikiArticles?: WikiArticle[]
  wikiCategories?: WikiCategory[]
  tags?: Tag[]
  labels?: Label[]
  stickers?: Sticker[]
}

/**
 * Resolve a Book's effective items by merging manual `book.items` with
 * auto-resolved items from `book.smartSources`.
 *
 * Algorithm:
 * 1. Mark all `book.items` as `source: "manual"`. These keep their
 *    existing fractional-indexing `order` keys.
 * 2. For each `smartSource` of kind="folder":
 *    a. Lookup folder by refId. Skip if not found (handles hard delete).
 *    b. Filter live notes: `n.folderIds.includes(refId) && !n.trashed`.
 *    c. Exclude entity ids in `book.excludeIds`.
 *    d. Exclude notes already manual-positioned (refId in book.items).
 *    e. Sort by `updatedAt desc` (newest first — Plot pattern).
 *    f. Generate auto chapter-heading `📁 {folder.name}` with
 *       deterministic id `auto-heading-${source.refId}`.
 *    g. Generate auto note items with deterministic id
 *       `auto-${source.refId}-${noteId}` and fractional keys >
 *       `lastManualOrder` (LOCKED #5c manual top / auto bottom).
 * 3. Sort merged result by `order` field.
 *
 * @returns ResolvedBookItem[] sorted by `order`. Manual items first,
 *          then auto items grouped by source with their chapter heading.
 */
export function resolveBookItems(
  book: Book,
  store: ResolverStore,
): ResolvedBookItem[] {
  // 1. Manual items
  // Tweak B: tag manual notes/wikis with sourceRefId if they'd also match
  // a smart source — UI uses this to render a subtle source badge so users
  // see "this manual note also lives in Daily Log folder". First-match wins
  // (multi-source dedup default per LOCKED §9). Probe order: most-specific
  // first (folder/category) so a manual note tagged with both a folder and
  // a tag shows the folder relation (more curatorial).
  const allSources = book.smartSources ?? []
  const folderSources = allSources.filter((s) => s.kind === "folder")
  const categorySources = allSources.filter((s) => s.kind === "category")
  const tagSources = allSources.filter((s) => s.kind === "tag")
  const labelSources = allSources.filter((s) => s.kind === "label")
  const stickerSources = allSources.filter((s) => s.kind === "sticker")
  const manualItems: ResolvedBookItem[] = book.items.map((item) => {
    let sourceRefId: string | undefined
    if (item.kind === "note") {
      const note = store.notes.find((n) => n.id === item.refId)
      if (note) {
        // Probe order: folder → label → tag → sticker
        sourceRefId =
          folderSources.find((s) => note.folderIds.includes(s.refId))?.refId ??
          labelSources.find((s) => note.labelId === s.refId)?.refId ??
          tagSources.find((s) => note.tags?.includes(s.refId))?.refId ??
          stickerSources.find((s) =>
            (store.stickers ?? []).some(
              (st) =>
                st.id === s.refId &&
                st.members.some((m) => m.kind === "note" && m.id === note.id),
            ),
          )?.refId
      }
    } else if (item.kind === "wiki") {
      const wiki = (store.wikiArticles ?? []).find((w) => w.id === item.refId)
      if (wiki) {
        // Probe order: category → tag → sticker (wiki has no folder/label here)
        sourceRefId =
          categorySources.find((s) => wiki.categoryIds?.includes(s.refId))?.refId ??
          tagSources.find((s) => wiki.tags?.includes(s.refId))?.refId ??
          stickerSources.find((s) =>
            (store.stickers ?? []).some(
              (st) =>
                st.id === s.refId &&
                st.members.some((m) => m.kind === "wiki" && m.id === wiki.id),
            ),
          )?.refId
      }
    }
    return {
      ...item,
      source: "manual" as const,
      ...(sourceRefId ? { sourceRefId } : {}),
    }
  })

  // 2. Compute lastManualOrder for auto-key seeding
  const sortedManualOrders = book.items
    .map((i) => i.order)
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
  const lastManualOrder =
    sortedManualOrders.length > 0
      ? sortedManualOrders[sortedManualOrders.length - 1]
      : null

  // Build sets for O(1) lookups
  const excludeSet = new Set(book.excludeIds ?? [])
  const manualNoteRefIds = new Set(
    book.items
      .filter((i): i is Extract<BookItem, { kind: "note" }> => i.kind === "note")
      .map((i) => i.refId),
  )
  const manualWikiRefIds = new Set(
    book.items
      .filter((i): i is Extract<BookItem, { kind: "wiki" }> => i.kind === "wiki")
      .map((i) => i.refId),
  )
  // Multi-source dedup: an entity that matches multiple sources appears
  // under the FIRST source only (LOCKED #11 / §9 Q4 default policy).
  // Single set is safe because Plot entity ids are UUIDs (no namespace
  // collision between note and wiki ids).
  const seenAutoRefIds = new Set<string>()

  const autoItems: ResolvedBookItem[] = []
  let prevOrder: string | null = lastManualOrder

  // Helper: sort entities by updatedAt desc with id tiebreaker for
  // deterministic output (notes + wikis share this pattern).
  const byUpdatedDesc = <T extends { id: string; updatedAt?: string }>(
    a: T,
    b: T,
  ): number => {
    const cmp = (b.updatedAt ?? "").localeCompare(a.updatedAt ?? "")
    return cmp !== 0 ? cmp : a.id.localeCompare(b.id)
  }

  // Helper: emit one auto chapter — heading + (note|wiki) items. Pure
  // append into autoItems; updates prevOrder + seenAutoRefIds in place.
  // sourceRefId is shared across heading + items so UI can scope actions
  // (e.g., addExcludeId for any auto child).
  const emitSection = (
    headingTitle: string,
    sourceRefId: string,
    candidates: Array<{ id: string; kind: "note" | "wiki" }>,
  ): void => {
    if (candidates.length === 0) return // LOCKED #10 v1.2

    const headingOrder = generateKeyBetween(prevOrder, null)
    autoItems.push({
      kind: "chapter-heading",
      id: `auto-heading-${sourceRefId}`,
      title: headingTitle,
      order: headingOrder,
      source: "auto",
      sourceRefId,
    })
    prevOrder = headingOrder

    for (const entity of candidates) {
      const entityOrder = generateKeyBetween(prevOrder, null)
      autoItems.push({
        kind: entity.kind,
        id: `auto-${sourceRefId}-${entity.id}`,
        refId: entity.id,
        order: entityOrder,
        source: "auto",
        sourceRefId,
      })
      prevOrder = entityOrder
      seenAutoRefIds.add(entity.id)
    }
  }

  // Helper: predicate for an entity that's still a valid auto candidate
  // (not excluded, not manual, not seen by an earlier source).
  const noteIsCandidate = (n: Note): boolean =>
    !n.trashed &&
    !excludeSet.has(n.id) &&
    !manualNoteRefIds.has(n.id) &&
    !seenAutoRefIds.has(n.id)
  const wikiIsCandidate = (w: WikiArticle): boolean =>
    !(w as { trashed?: boolean }).trashed &&
    !excludeSet.has(w.id) &&
    !manualWikiRefIds.has(w.id) &&
    !seenAutoRefIds.has(w.id)

  // 3. Process each smart source (all 5 kinds)
  for (const source of book.smartSources ?? []) {
    if (source.kind === "folder") {
      // Phase A — Note folder. Reverse N:M via Note.folderIds. Wiki
      // folders skip silently (PRD §5.3 + lib/types.ts Folder.kind).
      const folder = store.folders.find((f) => f.id === source.refId)
      if (!folder || folder.kind !== "note") continue

      const candidates = store.notes
        .filter((n) => n.folderIds.includes(source.refId) && noteIsCandidate(n))
        .sort(byUpdatedDesc)
        .map((n) => ({ id: n.id, kind: "note" as const }))

      emitSection(`📁 ${folder.name}`, source.refId, candidates)
      continue
    }

    if (source.kind === "category") {
      // Phase B — Wiki category. DAG: WikiArticle.categoryIds is an
      // optional array (a wiki can sit in multiple categories).
      const category = (store.wikiCategories ?? []).find((c) => c.id === source.refId)
      if (!category) continue

      const candidates = (store.wikiArticles ?? [])
        .filter((w) => w.categoryIds?.includes(source.refId) && wikiIsCandidate(w))
        .sort(byUpdatedDesc)
        .map((w) => ({ id: w.id, kind: "wiki" as const }))

      emitSection(`📚 ${category.name}`, source.refId, candidates)
      continue
    }

    if (source.kind === "tag") {
      // Phase C — Tag is the only cross-entity source: both Note.tags
      // and WikiArticle.tags are string[] referencing Tag.id. Combined
      // candidate list is sorted by updatedAt desc together (interleaved).
      const tag = (store.tags ?? []).find((t) => t.id === source.refId)
      if (!tag) continue

      const tagged: Array<{ id: string; kind: "note" | "wiki"; updatedAt?: string }> = [
        ...store.notes
          .filter((n) => n.tags?.includes(source.refId) && noteIsCandidate(n))
          .map((n) => ({ id: n.id, kind: "note" as const, updatedAt: n.updatedAt })),
        ...(store.wikiArticles ?? [])
          .filter((w) => w.tags?.includes(source.refId) && wikiIsCandidate(w))
          .map((w) => ({ id: w.id, kind: "wiki" as const, updatedAt: w.updatedAt })),
      ].sort(byUpdatedDesc)

      emitSection(`# ${tag.name}`, source.refId, tagged)
      continue
    }

    if (source.kind === "label") {
      // Phase D — Label is notes-only. Note.labelId is a scalar (single
      // label per note), so the predicate is === (not includes).
      const label = (store.labels ?? []).find((l) => l.id === source.refId)
      if (!label) continue

      const candidates = store.notes
        .filter((n) => n.labelId === source.refId && noteIsCandidate(n))
        .sort(byUpdatedDesc)
        .map((n) => ({ id: n.id, kind: "note" as const }))

      emitSection(`🏷 ${label.name}`, source.refId, candidates)
      continue
    }

    if (source.kind === "sticker") {
      // Phase E — Sticker is 7-kind cross-entity, but Smart Book only
      // pulls note + wiki members (INVARIANT §2). Other kinds (tag /
      // label / category / file / reference) are filtered out at the
      // resolver — they never become book pages.
      const sticker = (store.stickers ?? []).find((st) => st.id === source.refId)
      if (!sticker) continue

      const memberNoteIds = new Set(
        sticker.members.filter((m) => m.kind === "note").map((m) => m.id),
      )
      const memberWikiIds = new Set(
        sticker.members.filter((m) => m.kind === "wiki").map((m) => m.id),
      )

      const candidates: Array<{ id: string; kind: "note" | "wiki"; updatedAt?: string }> = [
        ...store.notes
          .filter((n) => memberNoteIds.has(n.id) && noteIsCandidate(n))
          .map((n) => ({ id: n.id, kind: "note" as const, updatedAt: n.updatedAt })),
        ...(store.wikiArticles ?? [])
          .filter((w) => memberWikiIds.has(w.id) && wikiIsCandidate(w))
          .map((w) => ({ id: w.id, kind: "wiki" as const, updatedAt: w.updatedAt })),
      ].sort(byUpdatedDesc)

      emitSection(`✨ ${sticker.name}`, source.refId, candidates)
      continue
    }
  }

  // 4. Merge and sort by order
  return [...manualItems, ...autoItems].sort((a, b) =>
    a.order < b.order ? -1 : a.order > b.order ? 1 : 0,
  )
}
