/**
 * Smart Book resolver (Phase 5 / Phase A — folder source only).
 *
 * Pure function that combines a Book's manual items with auto-resolved
 * items from `book.smartSources`. Manual items always render top, auto
 * items bottom (LOCKED #5c). The output is a flat sorted array of
 * `ResolvedBookItem` — same shape as BookItem plus `source` provenance
 * for the UI to differentiate (e.g., disable drag handle on auto items).
 *
 * INVARIANT (smart-book-prd §2): AutoSource is a "supplier", not a
 * member kind. Folder source resolves Notes only via reverse N:M
 * (`Note.folderIds.includes(source.refId)`). Folder has no `noteIds`
 * field — `lib/types.ts:463` confirmed.
 *
 * Phase A scope: kind="folder" sources only. Other kinds silently
 * ignored (Phase B-E).
 *
 * Spec: `.omc/plans/smart-book-prd.md` §5.3 + §5.10.
 */

import { generateKeyBetween } from "fractional-indexing"
import type { Book, BookItem, Note, Folder } from "@/lib/types"

/**
 * BookItem with source provenance. The `source` field is in-memory only
 * (NOT persisted) — it tells the UI whether the item came from
 * `book.items` (manual) or was auto-generated by a smartSource (auto).
 *
 * `sourceRefId` is set on auto items so the UI can route "remove" to
 * `addExcludeId(refId)` (auto) vs `removeItemFromBook(itemId)` (manual).
 */
export type ResolvedBookItem = BookItem & {
  source: "manual" | "auto"
  /** For auto items, the smartSource.refId that generated this item. */
  sourceRefId?: string
}

/**
 * Minimal store snapshot the resolver needs. Decouples from PlotState
 * for testability.
 */
export interface ResolverStore {
  notes: Note[]
  folders: Folder[]
  // Phase B-E will add: wikiArticles, tags, labels, stickers, wikiCategories
}

/**
 * Resolve a Book's effective items by merging manual `book.items` with
 * auto-resolved items from `book.smartSources`.
 *
 * Algorithm:
 * 1. Mark all `book.items` as `source: "manual"`. These keep their
 *    existing fractional-indexing `order` keys.
 * 2. For each `smartSource` of kind="folder":
 *    a. Lookup folder by refId. Skip if not found (handles hard delete).
 *    b. Filter live notes: `n.folderIds.includes(refId) && !n.trashed`.
 *    c. Exclude entity ids in `book.excludeIds`.
 *    d. Exclude notes already manual-positioned (refId in book.items).
 *    e. Sort by `updatedAt desc` (newest first — Plot pattern).
 *    f. Generate auto chapter-heading `📁 {folder.name}` with
 *       deterministic id `auto-heading-${source.refId}`.
 *    g. Generate auto note items with deterministic id
 *       `auto-${source.refId}-${noteId}` and fractional keys >
 *       `lastManualOrder` (LOCKED #5c manual top / auto bottom).
 * 3. Sort merged result by `order` field.
 *
 * @returns ResolvedBookItem[] sorted by `order`. Manual items first,
 *          then auto items grouped by source with their chapter heading.
 */
export function resolveBookItems(
  book: Book,
  store: ResolverStore,
): ResolvedBookItem[] {
  // 1. Manual items
  // Tweak B: tag manual notes/wikis with sourceRefId if they'd also match
  // a smart source — UI uses this to render a subtle folder badge so users
  // see "this manual note also lives in Daily Log folder". Phase A: folder
  // kind only, first-match wins (multi-source dedup default).
  const folderSources = (book.smartSources ?? []).filter((s) => s.kind === "folder")
  const manualItems: ResolvedBookItem[] = book.items.map((item) => {
    let sourceRefId: string | undefined
    if (item.kind === "note" && folderSources.length > 0) {
      const note = store.notes.find((n) => n.id === item.refId)
      const matchingFolder = note
        ? folderSources.find((s) => note.folderIds.includes(s.refId))
        : undefined
      sourceRefId = matchingFolder?.refId
    }
    return {
      ...item,
      source: "manual" as const,
      ...(sourceRefId ? { sourceRefId } : {}),
    }
  })

  // 2. Compute lastManualOrder for auto-key seeding
  const sortedManualOrders = book.items
    .map((i) => i.order)
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
  const lastManualOrder =
    sortedManualOrders.length > 0
      ? sortedManualOrders[sortedManualOrders.length - 1]
      : null

  // Build sets for O(1) lookups
  const excludeSet = new Set(book.excludeIds ?? [])
  const manualNoteRefIds = new Set(
    book.items
      .filter((i): i is Extract<BookItem, { kind: "note" }> => i.kind === "note")
      .map((i) => i.refId),
  )
  // Multi-source dedup: a note that matches multiple sources appears
  // under the FIRST source only (LOCKED #11 / §9 Q4 default policy).
  const seenAutoRefIds = new Set<string>()

  const autoItems: ResolvedBookItem[] = []
  let prevOrder: string | null = lastManualOrder

  // 3. Process each smart source (Phase A: folder only)
  for (const source of book.smartSources ?? []) {
    if (source.kind !== "folder") continue // Phase B-E guard

    const folder = store.folders.find((f) => f.id === source.refId)
    if (!folder) continue // Hard delete safety
    // Phase A: kind="note" folder only. Wiki folders skip silently
    // (PRD §5.3 + lib/types.ts:485 Folder.kind invariant). Phase B
    // adds wiki folder support via wikiArticles filter.
    if (folder.kind !== "note") continue

    // Filter notes: live + in folder + not excluded + not manual + not seen
    const candidates = store.notes
      .filter(
        (n) =>
          n.folderIds.includes(source.refId) &&
          !n.trashed &&
          !excludeSet.has(n.id) &&
          !manualNoteRefIds.has(n.id) &&
          !seenAutoRefIds.has(n.id),
      )
      .sort((a, b) => {
        // updatedAt desc (newest first). Falls back to id for stability.
        const cmp = (b.updatedAt ?? "").localeCompare(a.updatedAt ?? "")
        return cmp !== 0 ? cmp : a.id.localeCompare(b.id)
      })

    // LOCKED #10 (revised v1.2): empty auto source = silent skip (no heading,
    // no items). Was "show heading only" — caused confusion when all notes
    // are already manual (every note dedup'd → orphan heading). Source
    // visibility is managed via SourcesSection chip; heading only adds
    // value when auto items follow it.
    if (candidates.length === 0) continue

    // Mark seen (multi-source dedup)
    for (const note of candidates) {
      seenAutoRefIds.add(note.id)
    }

    // Auto chapter-heading
    const headingOrder = generateKeyBetween(prevOrder, null)
    autoItems.push({
      kind: "chapter-heading",
      id: `auto-heading-${source.refId}`,
      title: `📁 ${folder.name}`,
      order: headingOrder,
      source: "auto",
      sourceRefId: source.refId,
    })
    prevOrder = headingOrder

    // Auto note items
    for (const note of candidates) {
      const noteOrder = generateKeyBetween(prevOrder, null)
      autoItems.push({
        kind: "note",
        id: `auto-${source.refId}-${note.id}`,
        refId: note.id,
        order: noteOrder,
        source: "auto",
        sourceRefId: source.refId,
      })
      prevOrder = noteOrder
    }
  }

  // 4. Merge and sort by order
  return [...manualItems, ...autoItems].sort((a, b) =>
    a.order < b.order ? -1 : a.order > b.order ? 1 : 0,
  )
}
