import type { Note, Folder, Tag, Label, NoteTemplate } from "../types"
import { workflowDefaults } from "./helpers"

export const SEED_FOLDERS: Folder[] = [
  { id: "folder-1", name: "Projects", color: "#5e6ad2", parentId: null, lastAccessedAt: null, pinned: false, pinnedOrder: 0, createdAt: new Date().toISOString() },
  { id: "folder-2", name: "Daily Log", color: "#45d483", parentId: null, lastAccessedAt: null, pinned: false, pinnedOrder: 0, createdAt: new Date().toISOString() },
]

export const SEED_TAGS: Tag[] = [
  { id: "tag-1", name: "important", color: "#e5484d" },
  { id: "tag-2", name: "reference", color: "#5e6ad2" },
]

export const SEED_LABELS: Label[] = [
  { id: "label-1", name: "Idea", color: "#7c66dc" },
  { id: "label-2", name: "Research", color: "#5e6ad2" },
  { id: "label-3", name: "Meeting", color: "#45d483" },
  { id: "label-4", name: "Diary", color: "#e5484d" },
  { id: "label-5", name: "Memo", color: "#f5a623" },
]

export const SEED_TEMPLATES: NoteTemplate[] = [
  {
    id: "tmpl-meeting",
    name: "Meeting Notes",
    description: "회의록 템플릿",
    icon: "📋",
    color: "#45d483",
    title: "Meeting - {date}",
    content: "## 참석자\n\n- \n\n## 안건\n\n1. \n\n## 결정사항\n\n- \n\n## Action Items\n\n- [ ] ",
    status: "capture",
    priority: "medium",
    labelId: "label-3",
    tags: [],
    folderId: null,
    pinned: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tmpl-daily",
    name: "Daily Log",
    description: "오늘의 기록",
    icon: "📝",
    color: "#5e6ad2",
    title: "Daily - {date}",
    content: "## Today\n\n### Done\n\n- \n\n### In Progress\n\n- \n\n### Notes\n\n",
    status: "inbox",
    priority: "none",
    labelId: "label-4",
    tags: [],
    folderId: null,
    pinned: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tmpl-idea",
    name: "Idea",
    description: "아이디어 메모",
    icon: "💡",
    color: "#7c66dc",
    title: "",
    content: "## 아이디어\n\n\n\n## 왜?\n\n\n\n## 다음 단계\n\n- ",
    status: "inbox",
    priority: "none",
    labelId: "label-1",
    tags: [],
    folderId: null,
    pinned: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "tmpl-research",
    name: "Research",
    description: "리서치 노트",
    icon: "🔬",
    color: "#5e6ad2",
    title: "",
    content: "## 주제\n\n\n\n## 핵심 내용\n\n\n\n## 출처\n\n- \n\n## 인사이트\n\n",
    status: "capture",
    priority: "none",
    labelId: "label-2",
    tags: [],
    folderId: null,
    pinned: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const SEED_NOTES: Note[] = [
  {
    id: "note-1",
    title: "Welcome to Plot",
    content:
      "# Welcome to Plot\n\nThis is your new note-taking app.\n\n- Create notes with **markdown**\n- Organize with folders, categories, and tags\n- Pin important notes\n- Archive when done",
    contentJson: null,
    folderId: null,
    tags: ["tag-1", "tag-2"],
    labelId: null,
    status: "permanent",
    priority: "high",
    reads: 5,
    pinned: true,
    archived: false,
    trashed: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    ...workflowDefaults("permanent"),
    summary: "Introduction to the Plot note-taking app",
    preview: "Welcome to Plot This is your new note-taking app. - Create notes with markdown - Organize with folders, categories, and tags",
    linksOut: [],
  },
  {
    id: "note-2",
    title: "Quick thought",
    content: "This is an inbox note - a quick thought captured for later sorting.",
    contentJson: null,
    folderId: null,
    tags: [],
    labelId: "label-1",
    status: "inbox",
    priority: "none",
    reads: 1,
    pinned: false,
    archived: false,
    trashed: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
    ...workflowDefaults("inbox"),
    preview: "This is an inbox note - a quick thought captured for later sorting.",
    linksOut: [],
  },
  {
    id: "note-3",
    title: "Project planning",
    content: "## Q1 Goals\n\n1. Ship v1.0\n2. User testing\n3. Marketing launch",
    contentJson: null,
    folderId: "folder-1",
    tags: ["tag-1"],
    labelId: null,
    status: "capture",
    priority: "urgent",
    reads: 12,
    pinned: false,
    archived: false,
    trashed: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    ...workflowDefaults("capture"),
    triageStatus: "kept",
    preview: "Q1 Goals 1. Ship v1.0 2. User testing 3. Marketing launch",
    linksOut: [],
  },
  {
    id: "note-4",
    title: "API design notes",
    content: "REST vs GraphQL comparison for our new service.",
    contentJson: null,
    folderId: null,
    tags: ["tag-2"],
    labelId: "label-2",
    status: "permanent",
    priority: "medium",
    reads: 3,
    pinned: false,
    archived: false,
    trashed: false,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
    ...workflowDefaults("capture"),
    triageStatus: "kept",
    summary: "Comparison of REST and GraphQL approaches",
    preview: "REST vs GraphQL comparison for our new service.",
    linksOut: [],
  },
  {
    id: "note-5",
    title: "Meeting notes",
    content: "Discussed roadmap for Q2. Action items: finalize spec, assign tasks.",
    contentJson: null,
    folderId: "folder-2",
    tags: ["tag-1"],
    labelId: "label-3",
    status: "inbox",
    priority: "none",
    reads: 0,
    pinned: false,
    archived: false,
    trashed: false,
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    ...workflowDefaults("inbox"),
    preview: "Discussed roadmap for Q2. Action items: finalize spec, assign tasks.",
    linksOut: [],
  },
  {
    id: "note-6",
    title: "Bookmarks",
    content: "- https://example.com\n- https://another.dev",
    contentJson: null,
    folderId: null,
    tags: [],
    labelId: null,
    status: "inbox",
    priority: "low",
    reads: 0,
    pinned: false,
    archived: false,
    trashed: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    ...workflowDefaults("inbox"),
    source: "webclip",
    preview: "- https://example.com - https://another.dev",
    linksOut: [],
  },
]
