import type { Note, Folder, Tag, Category } from "../types"
import { workflowDefaults } from "./helpers"

export const SEED_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Work", color: "#5e6ad2" },
  { id: "cat-2", name: "Personal", color: "#26b5ce" },
  { id: "cat-3", name: "Ideas", color: "#f2994a" },
]

export const SEED_FOLDERS: Folder[] = [
  { id: "folder-1", name: "Projects", color: "#5e6ad2" },
  { id: "folder-2", name: "Daily Log", color: "#45d483" },
]

export const SEED_TAGS: Tag[] = [
  { id: "tag-1", name: "important", color: "#e5484d" },
  { id: "tag-2", name: "reference", color: "#5e6ad2" },
]

export const SEED_NOTES: Note[] = [
  {
    id: "note-1",
    title: "Welcome to Plot",
    content:
      "# Welcome to Plot\n\nThis is your new note-taking app.\n\n- Create notes with **markdown**\n- Organize with folders, categories, and tags\n- Pin important notes\n- Archive when done",
    contentJson: null,
    folderId: null,
    category: "cat-1",
    tags: ["tag-2"],
    status: "permanent",
    priority: "high",
    reads: 5,
    pinned: true,
    archived: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    ...workflowDefaults("permanent"),
    summary: "Introduction to the Plot note-taking app",
    project: null,
    projectLevel: null,
    preview: "Welcome to Plot This is your new note-taking app. - Create notes with markdown - Organize with folders, categories, and tags",
    linksOut: [],
  },
  {
    id: "note-2",
    title: "Quick thought",
    content: "This is an inbox note - a quick thought captured for later sorting.",
    contentJson: null,
    folderId: null,
    category: "",
    tags: [],
    status: "inbox",
    project: null,
    projectLevel: null,
    priority: "none",
    reads: 1,
    pinned: false,
    archived: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
    ...workflowDefaults("inbox"),
    preview: "This is an inbox note - a quick thought captured for later sorting.",
    linksOut: [],
  },
  {
    id: "note-3",
    title: "Project planning",
    content: "## Q1 Goals\n\n1. Ship v1.0\n2. User testing\n3. Marketing launch",
    contentJson: null,
    folderId: "folder-1",
    category: "cat-1",
    tags: ["tag-1"],
    status: "capture",
    project: "Q1 Goals",
    projectLevel: null,
    priority: "urgent",
    reads: 12,
    pinned: false,
    archived: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    ...workflowDefaults("capture"),
    triageStatus: "kept",
    preview: "Q1 Goals 1. Ship v1.0 2. User testing 3. Marketing launch",
    linksOut: [],
  },
  {
    id: "note-4",
    title: "API design notes",
    content: "REST vs GraphQL comparison for our new service.",
    contentJson: null,
    folderId: null,
    category: "cat-1",
    tags: ["tag-2"],
    status: "reference",
    project: null,
    projectLevel: null,
    priority: "medium",
    reads: 3,
    pinned: false,
    archived: false,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
    ...workflowDefaults("capture"),
    triageStatus: "kept",
    summary: "Comparison of REST and GraphQL approaches",
    preview: "REST vs GraphQL comparison for our new service.",
    linksOut: [],
  },
  {
    id: "note-5",
    title: "Meeting notes",
    content: "Discussed roadmap for Q2. Action items: finalize spec, assign tasks.",
    contentJson: null,
    folderId: "folder-2",
    category: "cat-1",
    tags: [],
    status: "inbox",
    project: null,
    projectLevel: null,
    priority: "none",
    reads: 0,
    pinned: false,
    archived: false,
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    ...workflowDefaults("inbox"),
    preview: "Discussed roadmap for Q2. Action items: finalize spec, assign tasks.",
    linksOut: [],
  },
  {
    id: "note-6",
    title: "Bookmarks",
    content: "- https://example.com\n- https://another.dev",
    contentJson: null,
    folderId: null,
    category: "cat-2",
    tags: [],
    status: "inbox",
    project: null,
    projectLevel: null,
    priority: "low",
    reads: 0,
    pinned: false,
    archived: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    ...workflowDefaults("inbox"),
    source: "webclip",
    preview: "- https://example.com - https://another.dev",
    linksOut: [],
  },
]
